services:
  mongo:
    restart: unless-stopped
    image: mongo:7.0.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  app:
    restart: unless-stopped
    build: 
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - PORT=3000
    env_file:
      - .env
    depends_on:
      - mongo
 