# Stage 1
FROM node:20.16-alpine as base

WORKDIR /app

# Copy the package.json files
COPY package.json ./
COPY tsconfig.json ./

# Install dependencies
RUN npm install 

# Copy the rest of the application code
COPY . .

RUN npx tsc -p .


# Stage 2
# FROM gcr.io/distroless/nodejs18-debian11

# WORKDIR /app
# COPY --from=base /app /app

# USER nonroot

# nest start
CMD ["npm", "run", "start"]
